/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        workspace: {
          dark: '#181818',
          panel: '#1f1f1f',
          tab: '#252526',
          tabInactive: '#2d2d2d',
          header: '#2d2d2d',
          border: '#3c3c3c',
          borderLight: '#454545',
          borderFocus: '#007acc',
          activeTab: '#1e1e1e',
          selection: '#094771',
          hover: '#2a2d2e',
          active: '#37373d',
          sidebar: '#181818',
          statusbar: '#007acc',
        },
        brand: {
          blue: '#007ACC',
          blueHover: '#1E90FF',
          haxeOrange: '#EA8220',
          haxeHover: '#FFA500',
          accent: '#007acc',
          accentHover: '#1e90ff',
        },
        ide: {
          bg: 'var(--ide-bg, #181818)',
          panel: 'var(--ide-panel, #1f1f1f)',
          header: 'var(--ide-header, #2d2d2d)',
          border: 'var(--ide-border, #3c3c3c)',
          text: 'var(--ide-text, #e0e0e0)',
          muted: 'var(--ide-muted, #858585)',
          selection: 'var(--ide-selection, #094771)',
          accent: 'var(--ide-accent, #007acc)',
          accentHover: 'var(--ide-accent-hover, #1e90ff)',
          error: 'var(--ide-error, #f87171)',
          warning: 'var(--ide-warning, #fbbf24)',
          success: 'var(--ide-success, #34d399)',
          info: 'var(--ide-info, #60a5fa)',
        },
        status: {
          error: '#f87171',
          errorBg: 'rgba(248, 113, 113, 0.15)',
          warning: '#fbbf24',
          warningBg: 'rgba(251, 191, 36, 0.15)',
          success: '#34d399',
          successBg: 'rgba(52, 211, 153, 0.15)',
          info: '#60a5fa',
          infoBg: 'rgba(96, 165, 250, 0.15)',
        },
      },
      fontSize: {
        '2xs': ['0.65rem', { lineHeight: '0.85rem' }],
        'xs': ['0.75rem', { lineHeight: '1rem' }],
        'sm': ['0.8125rem', { lineHeight: '1.125rem' }],
        'base': ['0.875rem', { lineHeight: '1.25rem' }],
      },
      fontFamily: {
        sans: ['Inter', 'Segoe UI', 'system-ui', '-apple-system', 'sans-serif'],
        mono: ['JetBrains Mono', 'Consolas', 'Fira Code', 'monospace'],
      },
      boxShadow: {
        'ide-panel': '0 2px 8px rgba(0, 0, 0, 0.4)',
        'ide-dropdown': '0 4px 16px rgba(0, 0, 0, 0.5)',
        'ide-modal': '0 8px 32px rgba(0, 0, 0, 0.6)',
      },
    },
  },
  plugins: [],
};
